# Problem 1

In [ ]:
# 1 - numpy kütüphanesini import edin

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin

# 3 - matris'in boyutunu öğrenin

# 4 - matris'i yeniden boyutlandırın

# 5 - matris'in boyut sayısını öğrenin


In [2]:
import numpy as np

# 0 ile 10 arasında 5 sayıdan oluşan matris üretmek
matris = np.random.randint(0, 10, (5))

# Matris'in boyutunu öğrenmek
boyut = matris.shape
print("Matris Boyutu:", boyut)

# Matris'i yeniden boyutlandırmak
matris = matris.reshape(1,5)
print("Yeniden boyutlandırılmış matris:", matris)

# Matris boyut sayısını öğrenmek
boyut_sayisi = matris.ndim
print("Matris Boyut Sayısı:", boyut_sayisi)


Matris Boyutu: (5,)
Yeniden boyutlandırılmış matris: [[8 1 2 1 0]]
Matris Boyut Sayısı: 2


# Problem 2

In [ ]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin

# 2 - Oluşturduğunuz matrisi parçalayın

# 3 - Parçalanmış matrisleri birleştirin


In [1]:
import numpy as np

# 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretmek
matris = np.arange(1, 11, 2).reshape(2, 2)
print("Matris:\n", matris)

# Matrisi parçalama
alt_matris1 = matris[:1, :]
alt_matris2 = matris[1:, :]
print("Alt Matris 1:\n", alt_matris1)
print("Alt Matris 2:\n", alt_matris2)

# Parçalanmış matrisleri birleştirme
birlesik_matris = np.concatenate((alt_matris1, alt_matris2), axis=0)
print("Birleştirilmiş Matris:\n", birlesik_matris)


ValueError: cannot reshape array of size 5 into shape (2,2)

# Problem 3

In [ ]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin

# 2 - matris'in özelliklerini inceleyin


In [3]:
import numpy as np

# 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretmek
matris = np.random.randint(low=5, high=101, size=(5, 10)) * 2
print("Matris:\n", matris)

# Matris özelliklerini incelemek
print("Boyut: ", matris.shape)
print("Toplam Eleman Sayısı: ", matris.size)
print("Veri Tipi: ", matris.dtype)
print("En Küçük Değer: ", matris.min())
print("En Büyük Değer: ", matris.max())
print("Ortalama: ", matris.mean())
print("Standart Sapma: ", matris.std())



Matris:
 [[ 24  20 200  86  32  92  46 172 176 140]
 [152 140  30 174  40 100 132 174 170  78]
 [110 110 130  42 114  44  48 164  52  62]
 [156 138 200 168  10 132  58  88  72 150]
 [ 48  94 146 112  58  24 120 192  38 176]]
Boyut:  (5, 10)
Toplam Eleman Sayısı:  50
Veri Tipi:  int32
En Küçük Değer:  10
En Büyük Değer:  200
Ortalama:  104.68
Standart Sapma:  55.58648756667397
